// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWDq1E6ItOPR9UpnNxLGUTrzAv9lctmcE',
    appId: '1:297030335653:web:ef4bc12a1fa8d09df6614c',
    messagingSenderId: '297030335653',
    projectId: 'tilapia-connect',
    authDomain: 'tilapia-connect.firebaseapp.com',
    storageBucket: 'tilapia-connect.appspot.com',
    measurementId: 'G-YVHNX5Z6DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWaBPBfhLDdhiHspdq0wgzgpU5r0NMBJo',
    appId: '1:297030335653:android:d8b81b081baf8786f6614c',
    messagingSenderId: '297030335653',
    projectId: 'tilapia-connect',
    storageBucket: 'tilapia-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4pFvyUCeNP_MdBv-ce8qnrDhU0fZ7mhU',
    appId: '1:297030335653:ios:0273db077f97d02cf6614c',
    messagingSenderId: '297030335653',
    projectId: 'tilapia-connect',
    storageBucket: 'tilapia-connect.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4pFvyUCeNP_MdBv-ce8qnrDhU0fZ7mhU',
    appId: '1:297030335653:ios:0273db077f97d02cf6614c',
    messagingSenderId: '297030335653',
    projectId: 'tilapia-connect',
    storageBucket: 'tilapia-connect.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWDq1E6ItOPR9UpnNxLGUTrzAv9lctmcE',
    appId: '1:297030335653:web:f1250ca29eedeaf3f6614c',
    messagingSenderId: '297030335653',
    projectId: 'tilapia-connect',
    authDomain: 'tilapia-connect.firebaseapp.com',
    storageBucket: 'tilapia-connect.appspot.com',
    measurementId: 'G-Q2R61TCCV4',
  );
}
